server:
  servlet.contextPath: /model
  
# Utilitzem WebLogic i ens connectem a la bdd via datasource definit al servidor
oracle:
    driverClassName: xxx
    databaseUrl: xxx
    username: xxx
    password: xxx
    dataSourceName: jdbc/MODEL
 
hibernate:
    showSql: true
    dialect: org.hibernate.dialect.Oracle10gDialect
    
cas:
    loginUrl: https://presso.upf.edu/CAS/index.php/login
    validateUrl: xxx
    returnUrl: https://presso.upf.edu/CAS/index.php
    logoutUrl: https://presso.upf.edu/CAS/index.php/logout