server:
  port: 8080
  servlet.contextPath: /model

# Utilitzem Tomcat (SpringBoot) i ens connectem a la bdd de manera directa.
oracle:
    driverClassName: oracle.jdbc.OracleDriver
    databaseUrl: jdbc:oracle:thin:@crsintscan-vip.s.upf.edu:1521/INTUTF
    username: desmodel
    password: mdl12
    dataSourceName: xxx
 
hibernate:
    showSql: true
    dialect: org.hibernate.dialect.Oracle10gDialect
    
cas:
    loginUrl: https://presso.upf.edu/CAS/index.php/login
    validateUrl: http://localhost:8080/model/login/cas
    returnUrl: https://presso.upf.edu/CAS/index.php
    logoutUrl: https://presso.upf.edu/CAS/index.php/logout
    
spring:
    thymeleaf.cache: false
    thymeleaf.check-template: true
    thymeleaf.check-template-location: true
    thymeleaf.content-type: text/html
    thymeleaf.enabled: true
    thymeleaf.encoding: UTF-8
    